parameters:
    database_driver:                      pdo_mysql
    database_host:                        db
    database_port:                        3306
    database_name:                        akeneo
    database_user:                        akeneo
    database_password:                    akeneo
    locale:                               en
    secret:                               somesecrettokenval
    product_index_name:                   akeneo_pim_product
    product_model_index_name:             akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts:                          'elastic:changeme@elasticsearch:9200'
