parameters:
    database_driver:                      pdo_mysql
    database_host:                        {{DBHOST}}
    database_port:                        3306
    database_name:                        akeneo_pim
    database_user:                        akeneo_pim
    database_password:                    {{MYSQLDBUSERPWD}}
    locale:                               en
    secret:                               {{SecretToken}}
    product_index_name:                   akeneo_pim_product
    product_model_index_name:             akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts:                          'elastic:changeme@elasticsearch:9200'
